@UnitConverter.Api_HostAddress = http://localhost:5117

PUT {{UnitConverter.Api_HostAddress}}/convert
Content-Type: application/json
{
  "category": "temperature",
  "fromUnit": "Celsius",
  "toUnit": "Fahrenheit",
  "value": 25
}

###
